In [1]:
import numpy as np
import torch
import torch.nn.functional as F

C:\Users\Mati\anaconda3\envs\master\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [ ]:
testuwa = torch.randn(3, 3, 3)

In [72]:
tensor = torch.randn(3, 3, 3)

In [73]:
tensor

tensor([[[ 0.1672,  1.0458,  0.5627],
         [ 1.2991, -1.3889,  0.8937],
         [ 0.0858,  1.0934,  0.2977]],

        [[ 1.0977,  0.7520,  0.7906],
         [ 0.2112, -0.3359, -1.1636],
         [-1.6091,  0.4361,  0.4542]],

        [[ 0.1530, -0.4246, -0.7641],
         [ 2.5847,  1.7922, -0.7811],
         [ 1.0675, -1.4717, -0.3632]]])

In [74]:
padded = F.pad(tensor, (1, 1, 1, 1), "constant", 0)

In [75]:
padded

tensor([[[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.1672,  1.0458,  0.5627,  0.0000],
         [ 0.0000,  1.2991, -1.3889,  0.8937,  0.0000],
         [ 0.0000,  0.0858,  1.0934,  0.2977,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000]],

        [[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  1.0977,  0.7520,  0.7906,  0.0000],
         [ 0.0000,  0.2112, -0.3359, -1.1636,  0.0000],
         [ 0.0000, -1.6091,  0.4361,  0.4542,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000]],

        [[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.1530, -0.4246, -0.7641,  0.0000],
         [ 0.0000,  2.5847,  1.7922, -0.7811,  0.0000],
         [ 0.0000,  1.0675, -1.4717, -0.3632,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000]]])

In [76]:
#windows and permutation

In [77]:
padded.shape

torch.Size([3, 5, 5])

In [78]:
padded = padded.permute((-1, 0, 1))
padded.shape

torch.Size([5, 3, 5])

In [79]:
padded = padded.unfold(1,3,1).unfold(2,3,1)

In [80]:
padded = padded.reshape(padded.shape[0],-1,*padded.shape[3:])

In [81]:
padded

tensor([[[[ 0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000]],

         [[ 0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000]],

         [[ 0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000]]],


        [[[ 0.0000,  0.1672,  1.2991],
          [ 0.0000,  1.0977,  0.2112],
          [ 0.0000,  0.1530,  2.5847]],

         [[ 0.1672,  1.2991,  0.0858],
          [ 1.0977,  0.2112, -1.6091],
          [ 0.1530,  2.5847,  1.0675]],

         [[ 1.2991,  0.0858,  0.0000],
          [ 0.2112, -1.6091,  0.0000],
          [ 2.5847,  1.0675,  0.0000]]],


        [[[ 0.0000,  1.0458, -1.3889],
          [ 0.0000,  0.7520, -0.3359],
          [ 0.0000, -0.4246,  1.7922]],

         [[ 1.0458, -1.3889,  1.0934],
          [ 0.7520, -0.3359,  0.4361],
          [-0.4246,  1.7922, -1.4717]],

         [[-1.3889,  1.0934,  0.0000],
     

In [51]:
padded = padded.permute((1,2,3,0))

In [52]:
padded

tensor([[[[0., 0., 0., 0., 0.],
          [0., 1., 1., 1., 0.],
          [0., 1., 1., 1., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 1., 1., 1., 0.],
          [0., 1., 1., 1., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 1., 1., 1., 0.],
          [0., 1., 1., 1., 0.]]],


        [[[0., 1., 1., 1., 0.],
          [0., 1., 1., 1., 0.],
          [0., 1., 1., 1., 0.]],

         [[0., 1., 1., 1., 0.],
          [0., 1., 1., 1., 0.],
          [0., 1., 1., 1., 0.]],

         [[0., 1., 1., 1., 0.],
          [0., 1., 1., 1., 0.],
          [0., 1., 1., 1., 0.]]],


        [[[0., 1., 1., 1., 0.],
          [0., 1., 1., 1., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 1., 1., 1., 0.],
          [0., 1., 1., 1., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 1., 1., 1., 0.],
          [0., 1., 1., 1., 0.],
          [0., 0., 0., 0., 0.]]]])

In [71]:


test = torch.tensor()

test

SyntaxError: invalid syntax (Temp/ipykernel_9660/2098137472.py, line 1)

In [64]:
unfolded = test.unfold(0, 3, 1)

unfolded

tensor([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5],
        [4, 5, 6],
        [5, 6, 7],
        [6, 7, 8],
        [7, 8, 9]])

In [68]:
unfolded.unfold(1, 2, 1)

tensor([[[1, 2],
         [2, 3]],

        [[2, 3],
         [3, 4]],

        [[3, 4],
         [4, 5]],

        [[4, 5],
         [5, 6]],

        [[5, 6],
         [6, 7]],

        [[6, 7],
         [7, 8]],

        [[7, 8],
         [8, 9]]])